name: Build the game

on:
  push:
    branches: [master-dev]
  pull_request:
    branches: [master-dev]
  workflow_dispatch:
jobs:
  
  BuildCaches:
    name: ${{ matrix.name }}
    permissions: write-all
    strategy:
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            setupScript: sh ./setup/unix.sh
            CACHE_NAME: P-Slice.1.0.desktop-cache

          - name: Mobile
            os: macos-latest
            setupScript: sh ./setup/mobile.sh
            CACHE_NAME: P-Slice.1.0.mobile-cache
    uses: ./.github/workflows/dependencies.yml
    with:
      os: ${{ matrix.os }}
      CACHE_NAME: ${{ matrix.CACHE_NAME }}
      setupScript: ${{ matrix.setupScript }}
  BuildMacos:
    name: macos
    needs: BuildCaches
    permissions: write-all
    uses: ./.github/workflows/mac-universal.yml
    with:
      exportPath: macos
      cachePath: P-Slice.1.0.build-macos
      cacheLibrariesPath: P-Slice.1.0.mobile-cache
      artifactName: P-Slice.1.0.macos
      artifactPath: export/release/macos/bin/*
  BuildDesktop:
    name: ${{ matrix.name }}
    needs: BuildCaches
    permissions: write-all
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: windows
            exportPath: windows
            artifactName: P-Slice.1.0.windows
            cacheLibrariesPath: P-Slice.1.0.desktop-cache
            cachePath: P-Slice.1.0.build-windows
            artifactPath: export\release\windows\bin\*
          - name: Linux
            os: ubuntu-22.04
            buildArgs: linux
            exportPath: linux
            artifactName: P-Slice.1.0.linux
            cachePath: P-Slice.1.0.build-linux
            cacheLibrariesPath: P-Slice.1.0.desktop-cache
            artifactPath: export/release/linux/bin/*

    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      cacheLibrariesPath: ${{ matrix.cacheLibrariesPath }}
      exportPath: ${{ matrix.exportPath }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}
      cachePath: ${{matrix.cachePath}}

  BuildMobile:
    permissions: write-all
    needs: BuildCaches
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Android
            os: macos-15
            exportPath: android
            buildArgs: "android"
            cacheLibrariesPath: P-Slice.1.0.mobile-cache
            artifactName: P-Slice.1.0.android
            cachePath: P-Slice.1.0.build-android
            artifactPath: "export/release/android/signed-bin/*.apk"
          - name: iOS
            os: macos-15
            buildArgs: "ios -nosign"
            exportPath: ios
            cacheLibrariesPath: P-Slice.1.0.mobile-cache
            artifactName: P-Slice.1.0.ios
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
            cachePath: P-Slice.1.0.build-ios
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      exportPath: ${{ matrix.exportPath }}
      artifactName: ${{ matrix.artifactName }}
      cacheLibrariesPath: ${{ matrix.cacheLibrariesPath }}
      artifactPath: ${{ matrix.artifactPath }}
      cachePath: ${{matrix.cachePath}}
